# Generated by Django 5.2.17 on 2026-09-15 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'tenants_organization',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('scope_type', models.CharField(choices=[('all', 'All'), ('assigned', 'Assigned')], default='assigned', max_length=50)),
                ('is_org_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='所属の一時停止用フラグ。論理削除とは別に、将来的な休止・承認待ち・一時無効化などの運用を想定して保持する。')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'db_table': 'tenants_membership',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('resource', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'tenants_permissions',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['resource', 'action'], name='tenants_per_resourc_b20b8b_idx'), models.Index(fields=['resource'], name='tenants_per_resourc_57e01a_idx')],
                'constraints': [models.UniqueConstraint(fields=('resource', 'action'), name='uniq_permission_resource_action')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.organization')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='tenants.permission')),
            ],
            options={
                'db_table': 'tenants_roles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='tenants.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_links', to='tenants.role')),
            ],
            options={
                'verbose_name': 'Membership Role',
                'verbose_name_plural': 'Membership Roles',
                'db_table': 'tenants_membership_role',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='memberships', through='tenants.MembershipRole', to='tenants.role'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_active_role_name_per_organization'),
        ),
        migrations.AddIndex(
            model_name='membershiprole',
            index=models.Index(fields=['membership', 'role'], name='tenants_mem_members_28ea67_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiprole',
            index=models.Index(fields=['role'], name='tenants_mem_role_id_739504_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershiprole',
            constraint=models.UniqueConstraint(fields=('membership', 'role'), name='uniq_membership_role'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'user'], name='tenants_mem_organiz_684c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'is_org_admin'], name='tenants_mem_organiz_b26759_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'is_active'], name='tenants_mem_organiz_f81ea1_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='uniq_membership_user_organization'),
        ),
    ]
