# Generated by Django 5.2.17 on 2026-09-24 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipInvitation',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='招待先メールアドレス')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='招待トークン')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=50, verbose_name='ステータス')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='tenants.membership', verbose_name='招待者')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Invitations', to='tenants.organization', verbose_name='組織')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.role', verbose_name='権限')),
            ],
            options={
                'verbose_name': 'Membership Invitation',
                'verbose_name_plural': 'Membership Invitations',
                'db_table': 'tenants_membership_invitation',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['token'], name='tenants_mem_token_835a26_idx'), models.Index(fields=['email', 'status'], name='tenants_mem_email_4d053d_idx'), models.Index(fields=['organization', 'status'], name='tenants_mem_organiz_5e5567_idx'), models.Index(fields=['expires_at'], name='tenants_mem_expires_347907_idx')],
            },
        ),
    ]
