# Generated by Django 5.2.17 on 2026-09-21 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=50, verbose_name='ステータス')),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='組織名')),
                ('organization_slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='組織スラッグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'accounts_email_verification_token',
                'indexes': [models.Index(fields=['token'], name='accounts_em_token_5a6f4a_idx'), models.Index(fields=['email', 'status'], name='accounts_em_email_44b431_idx'), models.Index(fields=['expires_at'], name='accounts_em_expires_af5955_idx')],
            },
        ),
    ]
