# Generated by Django 5.2.17 on 2026-09-26 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='新しいメールアドレス'),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='token_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_change', 'Password Change'), ('email_change', 'Email Change')], default='registration', max_length=50, verbose_name='トークンタイプ'),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['token_type', 'status'], name='accounts_em_token_t_d7a05f_idx'),
        ),
    ]
