# Generated by Django 5.2.17 on 2026-09-15 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('audit_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('audit_user_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('tenant_escape', 'テナント境界違反試行'), ('permission_denied', '権限不足アクセス試行'), ('deleted_data_access', '論理削除済みデータアクセス試行')], max_length=50)),
                ('attempted_organization_slug', models.SlugField(blank=True, max_length=100)),
                ('target_resource', models.CharField(blank=True, max_length=100)),
                ('target_resource_id', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True, help_text='追記事項、補足説明、判定理由など')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'db_table': 'audit_security_event',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['audit_user_email'], name='audit_secur_audit_u_ec1141_idx'), models.Index(fields=['user', 'event_type', 'created_at'], name='audit_secur_user_id_398957_idx'), models.Index(fields=['ip_address', 'event_type', 'created_at'], name='audit_secur_ip_addr_215b36_idx'), models.Index(fields=['attempted_organization_slug', 'created_at'], name='audit_secur_attempt_cec3bb_idx')],
            },
        ),
    ]
