# Generated by Django 5.2.17 on 2026-09-15 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='運用上の利用可否フラグ。status が業務状態を表すのに対し、こちらは将来的な一時停止・公開停止などの用途を想定する。')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_products', to='tenants.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.organization')),
            ],
            options={
                'db_table': 'products_product',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='tenants.membership')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_links', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Assignee',
                'verbose_name_plural': 'Product Assignees',
                'db_table': 'products_product_assignee',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_products', through='products.ProductAssignee', to='tenants.membership'),
        ),
        migrations.AddIndex(
            model_name='productassignee',
            index=models.Index(fields=['product', 'membership'], name='products_pr_product_24c4de_idx'),
        ),
        migrations.AddIndex(
            model_name='productassignee',
            index=models.Index(fields=['membership'], name='products_pr_members_72231c_idx'),
        ),
        migrations.AddConstraint(
            model_name='productassignee',
            constraint=models.UniqueConstraint(fields=('product', 'membership'), name='uniq_product_assignee'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization'], name='products_pr_organiz_d1a778_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'created_at'], name='products_pr_organiz_9534a7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'name'], name='products_pr_organiz_f39bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'status'], name='products_pr_organiz_c7c18b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'is_active'], name='products_pr_organiz_32f9ce_idx'),
        ),
    ]
